bundler_args: ""
before_install:
  - sudo add-apt-repository ppa:fta/dev -y
  - sudo apt-get update
  - sudo apt-get install -y nodejs closure-linter
  - npm install -g coffeelint
  - rvm default do gem install execjs
  - git config --global user.name "Pre Commit Closure Linter"
  - git config --global user.email "vzevan+travis@gmail.com"
language: ruby
rvm:
  - ruby-1.9.3
  - ruby-2.0.0
  - ruby-2.1
  - jruby
matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby
